### ISSUE TITLE
lvm vgremove --force is not enough sometimes

### ISSUE THREAD

**Issue by raharper** [project-machine/disko#127]
On a system with a damaged ThinPool LV, the RemoveVG() call will invoke `lvm vgremove --force <lv>` and this command returns 5, and mentioning that there is a thin pool transaction_id mismatch.

Adding an extra '--force' to the command will more forcefully remove the vg, with more warnings in the output.

**Comment by smoser** [comment]
I'm pretty sure this was fixed by https://github.com/project-machine/disko/pull/129.
reopen if that is wrong.
